Add Species and Owners Tables Update Animals Table - Add new queries
chelobotix/Vet-clinic-database pull request #4
Opened 2023-04-05 21:20 UTC by chelobotix

In this PR I fulfilled the following tasks:
- [x] Create a table named owners with the following columns:
id: integer (set it as autoincremented PRIMARY KEY)
full_name: string
age: integer
- [x] Create a table named species with the following columns:
id: integer (set it as autoincremented PRIMARY KEY)
name: string
- [x] Modify animals table:
Make sure that id is set as autoincremented PRIMARY KEY
Remove column species
Add column species_id which is a foreign key referencing species table
Add column owner_id which is a foreign key referencing the owners table
- [x] Insert the following data into the owners table:
Sam Smith 34 years old.
Jennifer Orwell 19 years old.
Bob 45 years old.
Melody Pond 77 years old.
Dean Winchester 14 years old.
Jodie Whittaker 38 years old.
- [x] Insert the following data into the species table:
Pokemon
Digimon
- [x] Modify your inserted animals so it includes the species_id value:
If the name ends in "mon" it will be Digimon
All other animals are Pokemon
- [x] Modify your inserted animals to include owner information (owner_id):
Sam Smith owns Agumon.
Jennifer Orwell owns Gabumon and Pikachu.
Bob owns Devimon and Plantmon.
Melody Pond owns Charmander, Squirtle, and Blossom.
Dean Winchester owns Angemon and Boarmon.
- [x] Write queries (using JOIN) to answer the following questions:
What animals belong to Melody Pond?
![1](https://user-images.githubusercontent.com/65084923/230213955-3ad79014-c286-4623-a4f4-67faafa99c58.jpg)

List of all animals that are pokemon (their type is Pokemon).
![2](https://user-images.githubusercontent.com/65084923/230213970-d0ae81f6-cb24-4c09-a4a7-b00cfa21b6cb.jpg)

List all owners and their animals, remember to include those that don't own any animal.
![3](https://user-images.githubusercontent.com/65084923/230214006-7db3e6c2-0476-4e92-95aa-fed975c64e24.jpg)

How many animals are there per species?
![4](https://user-images.githubusercontent.com/65084923/230214033-0c41cf7c-914a-40bf-acb3-684e58d98753.jpg)

List all Digimon owned by Jennifer Orwell.
![5](https://user-images.githubusercontent.com/65084923/230214060-acc6cd04-cfde-484a-88de-98fd5125ffe2.jpg)

List all animals owned by Dean Winchester that haven't tried to escape.
![6](https://user-images.githubusercontent.com/65084923/230214088-df57f3fb-308c-4178-a282-4d3f41cf5e9f.jpg)

Who owns the most animals?
![7](https://user-images.githubusercontent.com/65084923/230214098-377e7de7-b560-4671-859a-11f3b43fa07d.jpg)

2023-04-05 21:57 UTC, codecaiine requested changes
Hi @chelobotix   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Great schema implementation ✔️ 
- Good joining table queries set up ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 21:57 UTC, codecaiine commented on schema.sql
> +ALTER TABLE animals
- I noticed that this query is not correct, if you wanted to remove the species column which is Varchar, not id , your query should look like this **ALTER TABLE tbl_name DROP COLUMN col_name;** . Please fix it in order to make query works as expected  and also add more query 👍

2023-04-06 14:17 UTC, chelobotix commented
The observation has been fixed.
Thanks

2023-04-06 14:44 UTC, Davidosky007 approved these changes
Hi @chelobotix 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well written PR 👍 
* Good looking readme 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 15:13 UTC, merged